[build]
  publish = "dist/"
  command = "npm run build"

[[redirects]]
  from = "/feed"
  to = "/feed.xml"
  status = 200
  force = true

[[redirects]]
  from = "/feed/atom.xml"
  to = "/feed.xml"
  status = 200
  force = true
